[settings]
lockfile = true
cargo.binstall = true
node.compile = false
node.gpg_verify = true
npm.bun = true
pipx.uvx = true
python.default_packages_file = "~/.config/mise/default-python-packages"
python.uv_venv_auto = true
experimental = true
disable_backends = ["asdf", "ubi"]
idiomatic_version_file_enable_tools = ["python"]

# [tool_alias]
# php = "vfox:mise-plugins/vfox-php"

[tool_alias.node.versions]
lts = "24"
lts-krypton = "24"
lts-jod = "22"
lts-iron = "20"
lts-hydrogen = "18"
rolling = "26"

[tool_alias.java.versions]
lts = "corretto-25"
rolling = "corretto-26"

[tools]
# Pre-reqs
cargo-binstall = "latest"
cosign = "latest"
usage = "latest"
uv = "latest"
# Packages
aws-cli = "latest"
bat = "latest"
biome = "latest"
bitwarden = "latest"
bottom = "latest"
bun = "latest"
cmake = "latest"
coreutils = "latest"
delta = "latest"
deno = "latest"
dotenv-linter = "latest"
dotnet = "latest"
editorconfig-checker = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
gitleaks = "latest"
glab = "latest"
glow = "latest"
go = "latest"
java = "lts"
jq = "latest"
just = "latest"
lazygit = "latest"
markdownlint-cli2 = "latest"
node = "lts"
openbao = "latest"
opentofu = "latest"
packer = "latest"
# php = "latest"
prek = "latest"
python = "latest"
ripgrep = "latest"
ruby = "latest"
ruff = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
snyk = "latest"
sops = "latest"
starship = "latest"
stylua = "latest"
taplo = "latest"
television = "latest"
terraform = "latest"
tmux = "latest"
ty = "latest"
typos = "latest"
typst = "latest"
yamlfmt = "latest"
yamllint = "latest"
yq = "latest"
zig = "latest"
"aqua:neovim" = "latest"
"cargo:dysk" = "latest"
"cargo:rmpc" = "latest"
"cargo:sheldon" = "latest"
"cargo:tree-sitter-cli" = "0.27"
"github:JetBrains/kotlin" = "latest"
"github:boyter/scc" = "latest"
"github:clever/csvlint" = "latest"
"github:tectonic-typesetting/tectonic" = "latest"
"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:aws-cdk" = "latest"
"npm:typescript" = "latest"
"npm:wsl-open" = "latest"
