#!/usr/bin/env bash
# User dependent .bash_profile file

export BASHRC_LOGS=1

function log_profile() {
  if [[ ${BASHRC_LOGS:-0} -eq 1 ]]; then
    local log_file stamp
    log_file="${USER_DIRS_PROFILE:-${HOME}/profile}/bashrc.log"
    stamp="$(/usr/bin/date '+%F %I:%M:%S.%N %p')"

    echo -e "${stamp}: $1" >>"${log_file}"
  fi
}

function source_profile_script {
  # Only load it if necessary
  if [[ "${BASE_PROFILE_LOADED:-0}" -ne 1 ]]; then
    local dotfiles profile_script

    # Load my base-profile to setup the profile paths
    #
    # Bash_profile and Bashrc are the only locations where this extensive search for dotfiles should
    # need to be used. After the profile is loaded, all other scripts\code should be able to simply
    # use the environment variables or the user_dirs utility to find locations.
    dotfiles="${USER_DIRS_DOTFILES:-}"
    if [[ ! -d "${dotfiles}" ]]; then
      if command -v "user_dirs" &>/dev/null; then
        dotfiles=$(user_dirs DOTFILES)
      fi
    fi
    if [[ ! -d "${dotfiles}" ]]; then
      dotfiles="${HOME}/.dotfiles-rc"
    fi
    if [[ ! -d "${dotfiles}" ]]; then
      log_profile "Unable to locate dotfiles directory."
      echo -e "Unable to locate dotfiles directory."
      return 1
    fi

    profile_script="${dotfiles}/shells/shared/base-profile.bash"
    if [[ -x "${profile_script}" ]]; then
      log_profile "Sourcing: ${profile_script}"
      # shellcheck source=/home/brennan/.dotfiles-rc/shells/shared/base-profile.bash
      builtin source "${profile_script}"
    fi
  fi
}

function profile_activate_mise_shims {
  local mise_exe="${USER_DIRS_LOCALBIN:-${HOME}/.local/bin}/mise"
  if [[ -x ${mise_exe} ]]; then
    log_profile "Activating mise shims"
    eval "$(${mise_exe} activate --shims bash)"
  fi
}

function bash_profile {
  log_profile "In bash_profile"
  log_profile "PATH: ${PATH}"
  log_profile "Base profile loaded: ${BASE_PROFILE_LOADED:-0}"
  if shopt -q login_shell; then log_profile 'Login shell'; else log_profile 'Non-login shell'; fi
  if [[ $- == *i* ]]; then log_profile 'Interactive shell'; else log_profile 'Non-interactive shell'; fi

  source_profile_script

  profile_activate_mise_shims

  log_profile "Profile PATH: ${PATH}"
  log_profile "Leaving bash_profile"
}

bash_profile "$@"
unset -f log_profile
unset -f source_profile_script
unset -f profile_activate_mise_shims
unset -f bash_profile
