#!/usr/bin/env bash
# ~/.bash_logout: executed by bash(1) when login shell exits.

function bash_logout {
  log "In bash_logout"
  if shopt -q login_shell; then log 'Login shell'; else log 'Non-login shell'; fi
  if [[ $- == *i* ]]; then log "Interractive shell"; else log "Non-interactive shell"; fi

  # when leaving the console clear the screen to increase privacy

  if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
  fi
}

bash_logout "$@"
