-- local now_if_args = Config.now_if_args

-- now_if_args(function()
--   vim.pack.add {
--     "https://github.com/iamcco/markdown-preview.nvim",
--   }
--
--   Config.on_packchanged("markdown-preview.nvim", { "update", "install" }, function()
--     vim.cmd("mkdp#util#install")
--   end, "Update Markdown Preview.")
--
--   vim.g.mkdp_refresh_slow = 1
--   vim.g.mkdp_page_title = "File: ${name} "
--   vim.g.mkdp_preview_options = {
--     mkit = {
--       html = true,
--       xhtmlOut = true,
--       breaks = true,
--       langPrefix = "language-",
--       linkify = true,
--       typographer = true,
--     },
--     disable_filename = true,
--   }
--
--   vim.keymap.set("n", "<leader>pv", function()
--     vim.cmd("MarkdownPreviewToggle")
--   end, { noremap = true, desc = "MD: [P]re[v]iew Markdown" })
-- end)
--
