---
version: 2
log-file: /home/brennan/.local/state/efm-log.txt
log-level: 1
root-markers:
  - .git/
lint-debounce: 1s

tools:
  csv-csvlint: &csv_csvlint
    lint-command: csvlint

  gitcommit-gitlint: &gitcommit-gitlint
    lint-command: gitlint
    lint-stdin: true
    lint-formats:
      - '%l: %m: "%r"'
      - "%l: %m"

  codespell: &codespell
    diagnostic-command: codespell ${filename}
    diagnostic-stdin: false
    diagnostic-formats:
      - "%f:%l: %m"
    diagnostic-severity: 3

languages:
  csv:
    - !!merge <<: *csv_csvlint

  gitcommit:
    - !!merge <<: *gitcommit-gitlint

  =:
    - !!merge <<: *codespell
